In [1]:
import pandas as pd

In [2]:
original = pd.read_table('../rawdata/md5sum.txt', header=None, sep='  ', names=['original', 'file'])

/tmp/tmp.y7NeDhQPOr/ipykernel_1945193/2545447668.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  original = pd.read_table('../rawdata/md5sum.txt', header=None, sep='  ', names=['original', 'file'])

In [3]:
original

,original,file
0,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
1,7e5290414ba015894858c14cd42a68ab,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
2,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
3,8973109a4e8f105e8bc287398fee1319,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
4,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
5,8be7fe0840b6097190150d33ee558325,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
6,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...
7,2c07a6a70f848ae9b621b08d5fbf3d9a,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...

In [4]:
new = pd.read_table('../rawdata/md5_checksums.txt', header=None, sep=' ', names=['file','new'])

In [5]:
new

,file,new
0,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
1,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,7e5290414ba015894858c14cd42a68ab
2,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
3,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,8973109a4e8f105e8bc287398fee1319
4,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
5,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,8be7fe0840b6097190150d33ee558325
6,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
7,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,2c07a6a70f848ae9b621b08d5fbf3d9a

In [6]:
df = pd.merge(original, new, on='file', how='outer')

In [7]:
df

,original,file,new
0,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
1,7e5290414ba015894858c14cd42a68ab,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,7e5290414ba015894858c14cd42a68ab
2,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
3,8973109a4e8f105e8bc287398fee1319,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,8973109a4e8f105e8bc287398fee1319
4,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
5,8be7fe0840b6097190150d33ee558325,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,8be7fe0840b6097190150d33ee558325
6,b6a98c009a7f9ba7be7bc059ee4e3fda,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,b6a98c009a7f9ba7be7bc059ee4e3fda
7,2c07a6a70f848ae9b621b08d5fbf3d9a,3380__Merge-sample-PASABC-from-flowcell-HTNFLD...,2c07a6a70f848ae9b621b08d5fbf3d9a

In [8]:
df['original'] == df['new']

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
dtype: bool